awesome-academy/php_hn_fresher_mymusic

- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2022_03_08_022405_create_comments_table.php
- database/migrations/2022_03_08_022630_create_playlists_table.php
- database/migrations/2022_03_08_022807_create_songs_table.php
- database/migrations/2022_03_08_023827_create_albums_table.php
- database/migrations/2022_03_08_024026_create_authors_table.php
- database/migrations/2022_03_08_024531_create_categories_table.php
- database/migrations/2022_03_08_024817_add_user_id_to_playlists_table.php
- database/migrations/2022_03_08_025148_add_song_id_and_user_id_to_comments_table.php
- database/migrations/2022_03_08_025149_create_playlist_song_table.php
- database/migrations/2022_03_08_025621_add_album_id_to_songs_table.php
- database/migrations/2022_03_08_030058_add_author_id_to_albums_table.php
- database/migrations/2022_03_08_030059_create_author_song_table.php
- database/migrations/2022_03_08_030060_create_category_song_table.php
- [#46714](https://edu-redmine.sun-asterisk.vn/issues/46714)
- Tạo migration cho project
- N/A.
> [Task#46714] Tạo Migration

- app/Models/Album.php
- app/Models/Author.php
- app/Models/Category.php
- app/Models/Comment.php
- app/Models/Playlist.php
- app/Models/Song.php
- app/Models/User.php
- [#46715](https://edu-redmine.sun-asterisk.vn/issues/46715)
- Tạo Models và Relationship cho model tương ứng với các bảng trong DB
- N/A.
- N/A.
##DATABASE
> [Task#46715] Create Model Relationship

- .bowerrc
- .gitignore
- bower.json
- [#46823](https://edu-redmine.sun-asterisk.vn/issues/46823)
- Cài đặt bower gồm các package frontEnd sử dụng trong project
- N/A.
- N/A.
> [Task #46823]: Init Bower

- .sun-ci.yml
> Check Ci file

- .gitignore
- app/Http/Controllers/AuthController.php
- public/mix-manifest.json
- resources/css/app.css
- resources/css/login.css
- resources/css/style.css
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/layouts/auth.blade.php
- resources/views/pages/forgot-password.blade.php
- resources/views/pages/login.blade.php
- routes/web.php
- [#46821](https://edu-redmine.sun-asterisk.vn/issues/46821)
- Tạo giao diện cho trang đăng nhập , quên mật khẩu
- N/A.
- N/A.
>  [Task #46821]: Tạo giao diện đăng nhập , quên mật khẩu

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Kernel.php
- app/Http/Middleware/CheckAdmin.php
- app/Providers/RouteServiceProvider.php
- config/session.php
- resources/lang/en/auth.php
- resources/views/pages/login.blade.php
- [#46719](https://edu-redmine.sun-asterisk.vn/issues/46719)
- Xử lý logic đăng nhập
- N/A.
- N/A.
> [Task#46719]Xử lý logic đăng nhập

- app/Helpers/Helpers.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/Auth/VerificationController.php
- app/Models/User.php
- config/filesystems.php
- resources/css/register.css
- resources/css/style.css
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/pages/register.blade.php
- resources/views/pages/unverified.blade.php
- routes/web.php
- [#46720](https://edu-redmine.sun-asterisk.vn/issues/46720)
- Xử lý logic đăng ký
- Xác thực tài khoản
- N/A.
- N/A.
> [Task #46720] Xử lý logic đăng ký

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/Auth/ResetPasswordController.php
- resources/css/login.css
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/pages/forgot-password.blade.php
- resources/views/pages/login.blade.php
- resources/views/pages/passwords/reset-password.blade.php
- [#46721](https://edu-redmine.sun-asterisk.vn/issues/46721)
- Xử lý logic quên mật khẩu, đổi mật khẩu
- N/A.
- N/A.
> [Task#46721] Xử lý logic quên mật khẩu

- app/Repositories/Admin/BaseRepository.php
- app/Repositories/Admin/BaseRepositoryInterface.php
- [#47004](https://edu-redmine.sun-asterisk.vn/issues/47004)
- Tạo repository cho admin
- N/A.
- N/A.
> [Task #47004]: Tạo admin repository

- app/Http/Controllers/Admin/AuthorController.php
- config/admin.php
- resources/css/admin.css
- resources/css/app.css
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/admin/author/create.blade.php
- resources/views/admin/author/edit.blade.php
- resources/views/admin/author/list.blade.php
- resources/views/admin/author/view.blade.php
- resources/views/components/breadcrumb.blade.php
- resources/views/components/card.blade.php
- resources/views/partials/admin/sidebar.blade.php
- routes/web.php
- [#46723](https://edu-redmine.sun-asterisk.vn/issues/46723)
Tạo giao diện chức năng quản lý nghệ sĩ
- N/A.
- N/A.
> [Task#46723] Tạo giao diện chức năng quản lý nghệ sĩ

- app/Http/Controllers/Admin/CategoryController.php
- config/admin.php
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/admin/categories/create.blade.php
- resources/views/admin/categories/edit.blade.php
- resources/views/admin/categories/list.blade.php
- resources/views/admin/categories/show.blade.php
- resources/views/components/breadcrumb.blade.php
- routes/web.php
- [#46732](https://edu-redmine.sun-asterisk.vn/issues/46732)
- Tạo giao diện chức năng quản lý danh mục
- N/A.
> [Task #46732]: Tạo giao diện chức năng quản lý danh mục

- app/Http/Controllers/Admin/AlbumController.php
- config/admin.php
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/admin/album/create.blade.php
- resources/views/admin/album/edit.blade.php
- resources/views/admin/album/list.blade.php
- resources/views/admin/album/view.blade.php
- routes/web.php
- [#46729](https://edu-redmine.sun-asterisk.vn/issues/46729)
- Tạo giao diện chức năng quản lý album
- N/A.
- N/A.
> [Task#46729]Tạo giao diện chức năng quản lý album

- app/Http/Controllers/Admin/AuthorController.php
- app/Http/Requests/Admin/AuthorStoreRequest.php
- app/Http/Requests/Admin/AuthorUpdateRequest.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Admin/Author/AuthorRepoInterface.php
- app/Repositories/Admin/Author/AuthorRepository.php
- app/Repositories/Admin/BaseRepository.php
- config/admin.php
- config/filesystems.php
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/admin/author/create.blade.php
- resources/views/admin/author/edit.blade.php
- resources/views/admin/author/list.blade.php
- resources/views/admin/author/view.blade.php
- [#46724](https://edu-redmine.sun-asterisk.vn/issues/46724)
- Xử lý logic chức năng quản lý nghệ sĩ
- N/A.
- N/A.
> [Task#46724]Xử lý logic thêm sửa xoá nghệ sĩ

- app/Http/Controllers/Admin/CategoryController.php
- app/Http/Requests/Admin/CategoryStoreRequest.php
- app/Models/Category.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Admin/BaseRepository.php
- app/Repositories/Admin/BaseRepositoryInterface.php
- app/Repositories/Admin/Category/CategoryRepository.php
- app/Repositories/Admin/Category/CategoryRepositoryInterface.php
- config/admin.php
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/admin/categories/create.blade.php
- resources/views/admin/categories/edit.blade.php
- resources/views/admin/categories/list.blade.php
- resources/views/admin/categories/show.blade.php
- [#46733](https://edu-redmine.sun-asterisk.vn/issues/46733)
-  Xử lý logic thêm sửa xoá danh mục cho admin
- N/A.
- N/A.
> [Task #46733]: Xử lý logic thêm sửa xoá danh mục cho admin

- app/Http/Controllers/Admin/AlbumController.php
- app/Http/Requests/Admin/AlbumStoreRequest.php
- app/Http/Requests/Admin/AlbumUpdateRequest.php
- app/Models/Album.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Admin/Album/AlbumRepoInterface.php
- app/Repositories/Admin/Album/AlbumRepository.php
- app/Repositories/Admin/BaseRepository.php
- app/Repositories/Admin/BaseRepositoryInterface.php
- config/admin.php
- resources/js/app.js
- resources/views/admin/album/create.blade.php
- resources/views/admin/album/edit.blade.php
- resources/views/admin/album/list.blade.php
- resources/views/admin/album/view.blade.php
- [#46730](https://edu-redmine.sun-asterisk.vn/issues/46730)
- Xử lý logic thêm sửa xoá album
- N/A.
- N/A.
> [Task#46730] Xử lý logic thêm sửa xoá album

- app/Http/Controllers/Admin/SongController.php
- bower.json
- config/admin.php
- resources/css/admin.css
- resources/js/admin/song.js
- resources/js/app.js
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/admin/songs/create.blade.php
- resources/views/admin/songs/edit.blade.php
- resources/views/admin/songs/list.blade.php
- resources/views/admin/songs/show.blade.php
- resources/views/components/modal.blade.php
- resources/views/layouts/admin.blade.php
- routes/web.php
- [#46735](https://edu-redmine.sun-asterisk.vn/issues/46735)
- Tạo giao diện chức năng quản lý bài hát cho admin
- N/A.
> [Task #46735]: Tạo giao diện chức năng quản lý bài hát cho admin

- app/Http/Controllers/User/HomeController.php
- app/Models/User.php
- resources/js/app.js
- resources/js/music-player.js
- resources/views/components/card.blade.php
- resources/views/components/header.blade.php
- resources/views/components/music-player.blade.php
- resources/views/layouts/user.blade.php
- resources/views/user/homepage.blade.php
- resources/views/welcome.blade.php
- routes/web.php
- [#47219](https://edu-redmine.sun-asterisk.vn/issues/47219)
- Xây dựng giao diện chức năng nghe nhạc
- N/A.
- N/A.
> [Task#47219]Xây dựng giao diên chức năng nghe nhạc

- .gitignore
- app/Http/Controllers/User/HomeController.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Admin/Album/AlbumRepoInterface.php
- app/Repositories/Admin/Album/AlbumRepository.php
- app/Repositories/Admin/Category/CategoryRepository.php
- app/Repositories/Admin/Category/CategoryRepositoryInterface.php
- app/Repositories/Admin/Song/SongRepository.php
- app/Repositories/Admin/Song/SongRepositoryInterface.php
- public/mix-manifest.json
- resources/js/user/app.js
- resources/views/layouts/user.blade.php
- resources/views/user/homepage.blade.php
- tests/Feature/ExampleTest.php
- webpack.mix.js
- [#47248](https://edu-redmine.sun-asterisk.vn/issues/47248)
- Xử lý logic chức năng nghe nhạc
- N/A.
- N/A.
> [Task#47248] Logic chức năng nghe nhạc

- app/Http/Controllers/User/HomeController.php
- app/Repositories/Admin/BaseRepository.php
- app/Repositories/Admin/BaseRepositoryInterface.php
- resources/js/user/ajax.js
- resources/js/user/app.js
- resources/js/user/music-player.js
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/components/card.blade.php
- resources/views/components/header.blade.php
- resources/views/components/list.blade.php
- resources/views/user/album.blade.php
- resources/views/user/author.blade.php
- resources/views/user/homepage.blade.php
- routes/web.php
- [#47311](https://edu-redmine.sun-asterisk.vn/issues/47311)
- Xây dựng chức năng nghe nhạc theo album
- N/A.
- N/A.
> [Task#47311] Chức năng nghe nhạc theo album

- app/Http/Controllers/User/PlaylistController.php
- app/Models/Song.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Admin/Playlist/PlaylistRepoInterface.php
- app/Repositories/Admin/Playlist/PlaylistRepository.php
- resources/js/user/ajax.js
- resources/js/user/app.js
- resources/js/user/music-player.js
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/components/sidebar.blade.php
- resources/views/components/user-modal.blade.php
- resources/views/user/playlist.blade.php
- routes/web.php
- [#46754](https://edu-redmine.sun-asterisk.vn/issues/46754)
Thiết kế giao diện quản lý Playlist
- N/A.
- N/A.
> [Task#46754] Thiết kế giao diện quản lý Playlist

- app/Http/Controllers/User/PlaylistController.php
- app/Models/Playlist.php
- app/Repositories/Admin/Playlist/PlaylistRepoInterface.php
- app/Repositories/Admin/Playlist/PlaylistRepository.php
- resources/js/user/ajax.js
- resources/js/user/app.js
- resources/js/user/music-player.js
- resources/views/components/music-player.blade.php
- resources/views/components/sidebar.blade.php
- resources/views/user/album.blade.php
- resources/views/user/author.blade.php
- resources/views/user/category.blade.php
- resources/views/user/homepage.blade.php
- resources/views/user/playlist.blade.php
- routes/web.php
- [#Ticket ID](https://edu-redmine.sun-asterisk.vn/issues/xxxx)
- Thực hiện logic các chức năng quản lý playlist : thêm,sửa,xóa playlist, thêm nhạc , xóa nhạc khỏi playlist
- N/A.
- N/A.
> [Task] Logic Playlist

- app/Helpers/Helpers.php
- app/Http/Controllers/User/SearchController.php
- app/Repositories/Admin/BaseRepository.php
- app/Repositories/Admin/BaseRepositoryInterface.php
- config/search.php
- resources/css/search.css
- resources/js/admin/axios.js
- resources/js/user/ajax.js
- resources/js/user/app.js
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/layouts/user.blade.php
- resources/views/user/author.blade.php
- resources/views/user/search.blade.php
- routes/web.php
- [#Ticket ID](https://edu-redmine.sun-asterisk.vn/issues/xxxx)
- Xử lý logic cho trang search
- N/A.
- N/A.
> [Task #xxxxx]: Xử lý logic cho trang search

- app/Http/Controllers/User/AccountController.php
- resources/css/style.css
- resources/lang/vi.json
- resources/views/components/header.blade.php
- resources/views/user/account/change-password.blade.php
- resources/views/user/account/edit.blade.php
- resources/views/user/account/show.blade.php
- resources/views/user/account/sidebar.blade.php
- routes/web.php
- [#Ticket ID](https://edu-redmine.sun-asterisk.vn/issues/xxxx)
- Tạo giao diện profile cho user
- N/A.
- N/A.
> [Task]:Tạo giao diện profile cho user

- app/Helpers/Helpers.php
- app/Http/Controllers/User/AccountController.php
- app/Http/Requests/User/AccountChangePasswordRequest.php
- app/Http/Requests/User/AccountUpdateRequest.php
- app/Providers/AppServiceProvider.php
- app/Repositories/User/UserRepoInterface.php
- app/Repositories/User/UserRepository.php
- app/Rules/SameWithCurrentPassword.php
- resources/views/admin/songs/list.blade.php
- resources/views/layouts/auth.blade.php
- resources/views/user/account/change-password.blade.php
- resources/views/user/account/edit.blade.php
- routes/web.php
- [#46740](https://edu-redmine.sun-asterisk.vn/issues/46740)
- Thay đổi thông tin cá nhân , mật khẩu của người dùng
- N/A.
- N/A.
> [Task #46740]: Thay đổi thông tin cá nhân , mật khẩu của người dùng

- app/Http/Controllers/Auth/VerificationController.php
- app/Http/Controllers/User/PlaylistController.php
- app/Repositories/Admin/Playlist/PlaylistRepoInterface.php
- app/Repositories/Admin/Playlist/PlaylistRepository.php
- resources/js/user/ajax.js
- resources/js/user/app.js
- resources/js/user/music-player.js
- resources/views/components/sidebar.blade.php
- resources/views/user/album.blade.php
- resources/views/user/author.blade.php
- resources/views/user/category.blade.php
- resources/views/user/homepage.blade.php
- resources/views/user/playlist.blade.php
- resources/views/user/track.blade.php
- routes/web.php
- [#47392](https://edu-redmine.sun-asterisk.vn/issues/47392)
Chức năng thêm bài hát vào danh sách ưa thích
- N/A.
- N/A.
> [Task#47392] Chức năng thêm bài hát vào danh sách ưa thích

- app/Http/Middleware/Locale.php
- app/Models/Playlist.php
- resources/css/admin.css
- resources/js/user/ajax.js
- resources/views/admin/album/create.blade.php
- resources/views/admin/album/edit.blade.php
- resources/views/admin/album/list.blade.php
- resources/views/admin/author/edit.blade.php
- resources/views/admin/author/list.blade.php
- resources/views/admin/songs/list.blade.php
- resources/views/components/header.blade.php
- resources/views/components/sidebar.blade.php
- resources/views/layouts/auth.blade.php
- resources/views/partials/admin/header.blade.php
- resources/views/user/playlist.blade.php
- [#47419](https://edu-redmine.sun-asterisk.vn/issues/47419)
- Kiểm tra lại giao diện và code
- N/A.
- N/A.
> [Task #47419]: Kiểm tra lại giao diện và code

- app/Http/Controllers/Admin/AlbumController.php
- app/Http/Controllers/Admin/CategoryController.php
- app/Http/Controllers/User/HomeController.php
- app/Models/Song.php
- app/Repositories/Admin/BaseRepository.php
- app/Repositories/Admin/BaseRepositoryInterface.php
- app/Repositories/Admin/Category/CategoryRepository.php
- app/Repositories/Admin/Category/CategoryRepositoryInterface.php
- app/Repositories/Admin/Song/SongRepository.php
- resources/js/admin/song.js
- resources/js/user/slick.js
- resources/views/admin/album/view.blade.php
- resources/views/admin/author/view.blade.php
- resources/views/admin/categories/show.blade.php
- resources/views/components/music-player.blade.php
- resources/views/user/homepage.blade.php
- resources/views/user/track.blade.php
- routes/web.php
- [#47435](https://edu-redmine.sun-asterisk.vn/issues/47435)
- Cập nhật quản lý admin, thêm bài hát vào category, album
- N/A.
- N/A.
> [Task#47435] Update admin manager

- app/Http/Controllers/Admin/AlbumController.php
- app/Http/Controllers/Admin/CategoryController.php
- app/Http/Controllers/User/HomeController.php
- app/Http/Controllers/User/PlaylistController.php
- app/Repositories/Admin/Playlist/PlaylistRepository.php
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/admin/album/view.blade.php
- resources/views/admin/author/view.blade.php
- resources/views/admin/categories/show.blade.php
- resources/views/admin/songs/list.blade.php
- resources/views/user/homepage.blade.php
- [#47466](https://edu-redmine.sun-asterisk.vn/issues/47466)
- Sửa lỗi auth và bổ sung i18n còn thiếu
- N/A.
- N/A.
> [Bug #47466]: Sửa lỗi auth và bổ sung i18n còn thiếu

- app/Http/Controllers/Admin/AlbumController.php
- app/Http/Controllers/Admin/CategoryController.php
- app/Http/Requests/Admin/AlbumUpdateRequest.php
- app/Http/Requests/Admin/AuthorStoreRequest.php
- app/Http/Requests/Admin/AuthorUpdateRequest.php
- app/Http/Requests/Admin/CategoryStoreRequest.php
- app/Http/Requests/Admin/CategoryUpdateRequest.php
- app/Http/Requests/Admin/SongStoreRequest.php
- app/Http/Requests/Admin/SongUpdateRequest.php
- resources/views/admin/categories/show.blade.php
- resources/views/user/track.blade.php
- [#Ticket ID](https://edu-redmine.sun-asterisk.vn/issues/47554)
Fix validate + convention
- N/A.
- N/A.
> [Bug#47554]Fix validate + convention

- .gitignore
- tests/Unit/Model/AuthorTest.php
- [#47611](https://edu-redmine.sun-asterisk.vn/issues/47611)
- Unit test author model
- N/A.
> [Task #47611]: Unit test author model

- .gitignore
- tests/Unit/Models/SongTest.php
- [#47600](https://edu-redmine.sun-asterisk.vn/issues/47600)
- Tạo unit test cho song model
- N/A.
- N/A.
> [Task#47600]UnitTest Song Model

- tests/Unit/Models/CategoryTest.php
- [#47620](https://edu-redmine.sun-asterisk.vn/issues/47620)
Xây dựng unit test cho Category Model
- N/A.
- N/A.
> [Task#47620]  Unit Test Category Model

- tests/Unit/Models/CommentTest.php
- tests/Unit/Models/PlaylistTest.php
- [#47621](https://edu-redmine.sun-asterisk.vn/issues/47621)
- Tạo Unit Test Playlist + Comment Model
- N/A.
- N/A.
> [Task#47621] Unit Test Playlist + Comment Model

- tests/Unit/Models/AlbumTest.php
- tests/Unit/Models/AuthorTest.php
- [#47619](https://edu-redmine.sun-asterisk.vn/issues/47619)
- Unit test album model
- N/A.
> [Task #47619]: Unit test album model

- app/Models/User.php
- tests/Unit/Models/UserTest.php
- [#47622](https://edu-redmine.sun-asterisk.vn/issues/47622)
- Unit test user model
- N/A.
> [Task #47622]: Unit test user model

- app/Http/Controllers/Admin/AlbumController.php
- database/factories/AlbumFactory.php
- database/factories/AuthorFactory.php
- tests/Unit/Http/Controllers/Admin/AlbumControllerTest.php
- [#Ticket ID](https://edu-redmine.sun-asterisk.vn/issues/47653)
- Tạo unit test cho album controller
- N/A.
- N/A.
> [Task#47653] Unit Test Album Controller

- app/Http/Controllers/Admin/SongController.php
- database/factories/AuthorFactory.php
- database/factories/SongFactory.php
- tests/Unit/Http/Controllers/Admin/SongControllerTest.php
- [#47654](https://edu-redmine.sun-asterisk.vn/issues/47654)
- Unit test song controller
- N/A.
> [Task #47654]: Unit test song controller

- composer.json
- composer.lock
- resources/views/pages/register.blade.php
- tests/Browser/Pages/HomePage.php
- tests/Browser/Pages/Page.php
- tests/Browser/RegisterTest.php
- tests/Browser/console/.gitignore
- tests/Browser/screenshots/.gitignore
- tests/Browser/source/.gitignore
- tests/DuskTestCase.php
- [#47680](https://edu-redmine.sun-asterisk.vn/issues/47680)
- Cài đặt laravel Dusk + Test View đăng ký
- N/A.
- N/A.
> [Task#47680]  Test Register VIew

- resources/views/pages/login.blade.php
- tests/Browser/LoginTest.php
- [#47689](https://edu-redmine.sun-asterisk.vn/issues/47689)
- Test login view
- N/A.
> [Task #47689]: Test login view

- app/Http/Controllers/Admin/UserController.php
- app/Models/User.php
- app/Repositories/User/UserRepoInterface.php
- app/Repositories/User/UserRepository.php
- config/admin.php
- resources/js/admin/axios.js
- resources/js/admin/user.js
- resources/js/app.js
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/admin/users/list.blade.php
- routes/web.php
- [#47222](https://edu-redmine.sun-asterisk.vn/issues/47222)
- Xử lý logic quản lý người dùng (hiển thị, block, unblock)
- N/A.
- N/A.
> [Task #47222]: Xử lý logic quản lý người dùng

- app/Http/Controllers/User/CommentController.php
- app/Http/Controllers/User/HomeController.php
- app/Models/Comment.php
- app/Providers/AppServiceProvider.php
- app/Repositories/User/CommentRepoInterface.php
- app/Repositories/User/CommentRepository.php
- resources/js/user/app.js
- resources/js/user/comment.js
- resources/views/user/song.blade.php
- routes/web.php
- tests/Unit/Models/CommentTest.php
- [#47682](https://edu-redmine.sun-asterisk.vn/issues/47682)
- Logic Comment
- N/A.
- N/A.
> [Task#47682] Logic Comment

- app/Http/Controllers/Auth/LoginController.php
- resources/lang/en.json
- resources/lang/vi.json
- [#47798](https://edu-redmine.sun-asterisk.vn/issues/47798)
- Xử lý lỗi user bị block những vẫn có thể đăng nhập
- N/A.
- N/A.
> [Bug #47798]: Xử lý lỗi user bị block những vẫn có thể đăng nhập

- composer.json
- composer.lock
- config/app.php
- package.json
- resources/js/bootstrap.js
- [#47806](https://edu-redmine.sun-asterisk.vn/issues/47806)
- Cài đặt pusher để gửi thông báo realtime
- N/A.
- N/A.
> [Task#47806] Set up Pusher

- tests/Unit/Models/UserTest.php
- [#47622](https://edu-redmine.sun-asterisk.vn/issues/47622)
-Bổ sung unit test cho user model
- N/A.
> [Task #47622]: Bổ sung unit test cho user model

- app/Events/NotificationEvent.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Models/User.php
- app/Notifications/RegisterNotification.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Admin/Playlist/PlaylistRepoInterface.php
- database/migrations/2022_03_31_130916_create_notifications_table.php
- resources/css/admin.css
- resources/js/admin/notification.js
- resources/js/app.js
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/partials/admin/header.blade.php
- [#47776](https://edu-redmine.sun-asterisk.vn/issues/47776)
- Tạo thông báo gửi đến admin khi có người dùng đăng ký
- N/A.
- N/A.
> [Task#47776] Notification register to admin

- database/factories/UserFactory.php
- tests/Unit/Http/Controllers/Admin/UserControllerTest.php
- [#47825](https://edu-redmine.sun-asterisk.vn/issues/47825)
- Unit test Admin/UserController
- N/A.
> [Task #47825]: Unit test Admin/UserController

- app/Http/Controllers/Admin/DashboardController.php
- tests/Unit/Http/Controllers/Admin/DashboardControllerTest.php
- [#47829](https://edu-redmine.sun-asterisk.vn/issues/47829)
- Unit test Admin/DashboardController
- N/A.
> [Task #47829]: Unit test Admin/DashboardController

- app/Helpers/Helpers.php
- app/Http/Controllers/Admin/NotificationController.php
- app/Http/Controllers/Admin/UserController.php
- app/Repositories/Admin/BaseRepository.php
- app/Repositories/Admin/BaseRepositoryInterface.php
- resources/css/admin.css
- resources/js/admin/notification.js
- resources/views/partials/admin/header.blade.php
- routes/web.php
- [#47830](https://edu-redmine.sun-asterisk.vn/issues/47830)
- Mark as read notification
- N/A.
- N/A.
> [Task#47830] Mark at read notification

- app/Http/Controllers/Admin/AuthorController.php
- app/Repositories/Admin/Author/AuthorRepository.php
- tests/Unit/Http/Controllers/Admin/AuthorControllerTest.php
- [#47843](https://edu-redmine.sun-asterisk.vn/issues/47843)
- Viết unit test Admin/AuthorController
- N/A.
> [Task #47843]: Unit test Admin/AuthorController

- app/Helpers/Helpers.php
- app/Http/Controllers/Admin/AuthorController.php
- app/Imports/AuthorImport.php
- composer.json
- composer.lock
- config/app.php
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/admin/author/list.blade.php
- routes/web.php
- [#47785](https://edu-redmine.sun-asterisk.vn/issues/47785)
- Import excel vào danh sách nghệ sĩ
- N/A.
- N/A.
> [Task#47785] Import excel

- app/Http/Controllers/Admin/CategoryController.php
- app/Repositories/Admin/Category/CategoryRepository.php
- database/factories/CategoryFactory.php
- tests/Unit/Http/Controllers/Admin/CategoryControllerTest.php
- [#47869](https://edu-redmine.sun-asterisk.vn/issues/47869)
- Unit test Admin/CategoryController
- N/A.
> [Task #47869]: Unit test Admin/CategoryController

- resources/js/user/ajax.js
- resources/js/user/app.js
- [#47936](https://edu-redmine.sun-asterisk.vn/issues/47936)
- Xử lý nút back trên giao diện ngươi dùng
- N/A.
- N/A.
> [Feature #47936] : Handle back button

- app/Helpers/Helpers.php
- app/Http/Controllers/Admin/AuthorController.php
- app/Http/Controllers/Admin/NotificationController.php
- app/Models/Notification.php
- database/factories/NotificationFactory.php
- tests/Unit/Http/Controllers/Admin/AuthorControllerTest.php
- tests/Unit/Http/Controllers/Admin/NotificationControllerTest.php
- tests/Unit/Http/Controllers/Admin/SongControllerTest.php
- [#47916](https://edu-redmine.sun-asterisk.vn/issues/47916)
- UnitTest Notification Controller
- UnitTest Import Excel
- N/A.
> [Task#47916] Controller unitTest

- resources/css/search.css
- resources/js/user/ajax.js
- resources/js/user/music-player.js
- resources/lang/en/auth.php
- resources/lang/vi/auth.php
- resources/views/layouts/user.blade.php
- resources/views/user/search.blade.php
- routes/web.php
- [#47948](https://edu-redmine.sun-asterisk.vn/issues/47948)
- Fix trang search
- Báo lỗi đăng nhập khi tạo playlist
- N/A.
- N/A.
> [Task #47948]: Fix sidebar in user page

- resources/js/user/ajax.js
- resources/js/user/app.js
- resources/js/user/music-player.js
- resources/views/components/music-player.blade.php
- resources/views/user/song.blade.php
- [#47998](https://edu-redmine.sun-asterisk.vn/issues/47998)
- Fix bug cannot play music in album page
- N/A.
- N/A.
> [Bug #47998]: Fix bug cannot play music in album page

- app/Http/Controllers/Admin/AuthorController.php
- resources/js/admin/dashboard.js
- resources/js/user/ajax.js
- resources/js/user/music-player.js
- resources/lang/en.json
- resources/lang/vi.json
- resources/views/layouts/admin.blade.php
- tests/Unit/Http/Controllers/Admin/AuthorControllerTest.php
- [#48023](https://edu-redmine.sun-asterisk.vn/issues/48023)
- Disable các nút trên thanh phát nhạc nếu người dùng chưa chọn bài hát nào
- Thông báo người dùng cần phải đăng nhập trước khi sử dụng các chức năng add to favorite và add to playlist
- Hiển thị message validate khi import excel
- N/A.
> [Bug #48023]: Music player and import excel validation message bug

- app/Repositories/User/UserRepository.php
- resources/js/user/comment.js
- resources/lang/en.json
- resources/lang/vi.json
- [#48100](https://edu-redmine.sun-asterisk.vn/issues/48100)
- Fix lại logic tính số lượng user của report
- Sửa lại ui và i18n cho comment
- N/A.
- N/A.
> [Bug #48100]: Weekly report calculate wrong and fix comment ui

- app/Exceptions/Handler.php
- app/Http/Controllers/Api/LoginController.php
- app/Http/Kernel.php
- composer.json
- composer.lock
- routes/api.php
- [#48364](https://edu-redmine.sun-asterisk.vn/issues/48364)
- Create API Login/Logout by Sanctum
-N/A
> [Task#48364] Login/Logout Api

- app/Http/Controllers/Api/RegisterController.php
- app/Http/Requests/Api/ApiRequest.php
- app/Http/Requests/Api/RegisterRequest.php
- app/Listeners/ManualSendEmailVerificationNotification.php
- app/Providers/EventServiceProvider.php
- resources/lang/en.json
- resources/lang/vi.json
- routes/api.php
- [#48396](https://edu-redmine.sun-asterisk.vn/issues/48396)
- Đăng ký tài khoản bằng API
- N/A.
> [Task #48396]: API register

- app/Http/Controllers/Api/AlbumController.php
- app/Http/Controllers/Api/LoginController.php
- app/Http/Kernel.php
- app/Http/Middleware/CheckAdminApi.php
- app/Http/Requests/Api/AlbumStoreRequest.php
- app/Http/Requests/Api/AlbumUpdateRequest.php
- app/Http/Requests/Api/LoginRequest.php
- app/Http/Resources/AlbumResource.php
- routes/api.php
- [#48496](https://edu-redmine.sun-asterisk.vn/issues/48496)
- Api album manager
- Fix Login validate
- N/A.
> [Task#48496] Api Album manager

- app/Http/Controllers/Api/CategoryController.php
- app/Http/Requests/Api/CategoryStoreRequest.php
- app/Http/Requests/Api/CategoryUpdateRequest.php
- app/Http/Resources/CategoryResource.php
- database/migrations/2022_04_20_082222_update_provider_nullable_in_users_table.php
- routes/api.php
- [#48555](https://edu-redmine.sun-asterisk.vn/issues/48555)
Category manager api
- N/A.
> [Task#48555] Category manager api
